site_name: CSD Portfolio and Activities Catalog
site_description: Computational Science Department Portfolio and Activities Catalog
repo_url: https://github.com/BNL-HPC/bnl-csd.github.io
repo_name: BNL-HPC/bnl-csd.github.io

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Exo 2
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  logo: assets/images/favicon.png

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md
  - Projects: projects.md
  - Products: products.md
  - Seminars & Talks: events.md
  - People: people.md
  - Archive:
      - Projects: archive/projects.md
      - People: archive/people.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

hooks:
  - docs/assets/hooks.py
