site_name: BNL Computational Science Department
site_description: BNL Computational Science Department main page
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Exo 2
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  logo: /pics/favicon.png

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Projects: projects.md
  - Collaborations: collaborations.md
  - Products: products.md
  - People: people.md
  - Archive:
      - Projects: archive/projects.md
      - Collaborations: archive/collaborations.md
      - People: archive/people.md

markdown_extensions:
  - attr_list
  - md_in_html
